### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by eckardt** [pyr/pickler#1]
Hi there,

I'm trying out `cyanite` and set it up to get its input from a carbon aggregator instance.

After receiving the pickled objects on port 2004 `cyanite` fails to unpickle the data (See stacktrace below for details).

I wonder if cyanite/pickler is supposed to be used with input coming from a specific version of carbon/python only. It would be interesting to know which version have been used for development.

```
WARN [2015-08-19 12:58:01,170] nioEventLoopGroup-2-2 - io.cyanite.input.pickle cannot deserialize pickle
clojure.lang.ExceptionInfo: invalid pickle data
        at clojure.core$ex_info.invoke(core.clj:4593) ~[cyanite.jar:na]
        at pickler.parser$fn__11576.invoke(parser.clj:101) ~[cyanite.jar:na]
        at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[cyanite.jar:na]
        at pickler.parser$raw__GT_ast$fn__11578.invoke(parser.clj:112) ~[cyanite.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[cyanite.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[cyanite.jar:na]
        at clojure.lang.Cons.next(Cons.java:39) ~[cyanite.jar:na]
        at clojure.lang.RT.next(RT.java:681) ~[cyanite.jar:na]
        at clojure.core$next__4112.invoke(core.clj:64) ~[cyanite.jar:na]
        at clojure.core$nthnext.invoke(core.clj:3038) ~[cyanite.jar:na]
        at pickler.parser$ast__GT_metrics.invoke(parser.clj:127) ~[cyanite.jar:na]
        at io.cyanite.input.pickle$pickle_lines.invoke(pickle.clj:16) ~[cyanite.jar:na]
        at io.cyanite.input.pickle$pipeline$fn__11614.invoke(pickle.clj:29) [cyanite.jar:na]
        at io.cyanite.input.pickle.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite.jar:na]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110) [cyanite.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

**Comment by eckardt** [comment]
After finding out about https://github.com/grobian/carbon-c-relay I figured out a way to aggregate metrics without relying on graphite's carbon-aggregator and the pickle protocol as an input altogether. So regarding graphite/cyanite this not an issue anymore for me.

**Comment by pyr** [comment]
Hi @eckardt,

Thanks for looking into this. I'll get on it.

**Comment by aww-yiss** [comment]
Hi @pyr,

I think I bumped into this issue as well, but reported in here originally:
  https://github.com/pyr/cyanite/issues/158

Is there anything you can think of which might prove problematic for pickle support? 

I've gotten Cyanite 0.5.1 setup, but it seems to not like the pickled data from our 0.9.10 carbon-relays

Let me know if I can provide any details to help sort this out!
